"""
ECO Code Loader and Cache
Provides opening names from ECO codes (B32, C45, etc.)
"""
import json
import logging
from typing import Dict, Optional
from pathlib import Path

logger = logging.getLogger(__name__)

# ECO Database - comprehensive ECO code to opening name mapping
ECO_DATABASE = {
    # A-codes: Irregular openings
    "A00": "Irregular Opening",
    "A01": "Larsen's Opening",
    "A02": "Bird's Opening",
    "A03": "Bird's Opening",
    "A04": "Reti Opening",
    "A05": "Reti Opening",
    "A06": "Reti Opening",
    "A07": "King's Indian Attack",
    "A08": "King's Indian Attack",
    "A09": "King's Indian Attack",
    "A10": "English Opening",
    "A11": "English Opening",
    "A12": "English Opening",
    "A13": "English Opening",
    "A14": "English Opening",
    "A15": "English Opening",
    "A16": "English Opening",
    "A17": "English Opening",
    "A18": "English Opening",
    "A19": "English Opening",
    "A20": "English Opening",
    "A21": "English Opening",
    "A22": "English Opening",
    "A23": "English Opening",
    "A24": "English Opening",
    "A25": "English Opening",
    "A26": "English Opening",
    "A27": "English Opening",
    "A28": "English Opening",
    "A29": "English Opening",
    "A30": "English Opening",
    "A31": "English Opening",
    "A32": "English Opening",
    "A33": "English Opening",
    "A34": "English Opening",
    "A35": "English Opening",
    "A36": "English Opening",
    "A37": "English Opening",
    "A38": "English Opening",
    "A39": "English Opening",
    "A40": "1.d4",
    "A41": "1.d4 e6",
    "A42": "1.d4 c5",
    "A43": "1.d4 c5",
    "A44": "1.d4 c5",
    "A45": "1.d4 Nf6",
    "A46": "1.d4 Nf6",
    "A47": "1.d4 Nf6",
    "A48": "1.d4 Nf6",
    "A49": "1.d4 Nf6",
    "A50": "1.d4 Nf6",
    "A51": "1.d4 Nf6",
    "A52": "1.d4 Nf6",
    "A53": "1.d4 Nf6",
    "A54": "1.d4 Nf6",
    "A55": "1.d4 Nf6",
    "A56": "1.d4 Nf6",
    "A57": "Benko Gambit",
    "A58": "Benko Gambit",
    "A59": "Benko Gambit",
    "A60": "Benoni Defense",
    "A61": "Benoni Defense",
    "A62": "Benoni Defense",
    "A63": "Benoni Defense",
    "A64": "Benoni Defense",
    "A65": "Benoni Defense",
    "A66": "Benoni Defense",
    "A67": "Benoni Defense",
    "A68": "Benoni Defense",
    "A69": "Benoni Defense",
    "A70": "Benoni Defense",
    "A71": "Benoni Defense",
    "A72": "Benoni Defense",
    "A73": "Benoni Defense",
    "A74": "Benoni Defense",
    "A75": "Benoni Defense",
    "A76": "Benoni Defense",
    "A77": "Benoni Defense",
    "A78": "Benoni Defense",
    "A79": "Benoni Defense",
    "A80": "Dutch Defense",
    "A81": "Dutch Defense",
    "A82": "Dutch Defense",
    "A83": "Dutch Defense",
    "A84": "Dutch Defense",
    "A85": "Dutch Defense",
    "A86": "Dutch Defense",
    "A87": "Dutch Defense",
    "A88": "Dutch Defense",
    "A89": "Dutch Defense",
    "A90": "Dutch Defense",
    "A91": "Dutch Defense",
    "A92": "Dutch Defense",
    "A93": "Dutch Defense",
    "A94": "Dutch Defense",
    "A95": "Dutch Defense",
    "A96": "Dutch Defense",
    "A97": "Dutch Defense",
    "A98": "Dutch Defense",
    "A99": "Dutch Defense",
    
    # B-codes: 1.e4 c5 (Sicilian)
    "B00": "Sicilian Defense",
    "B01": "Scandinavian Defense",
    "B02": "Alekhine's Defense",
    "B03": "Alekhine's Defense",
    "B04": "Alekhine's Defense",
    "B05": "Alekhine's Defense",
    "B06": "Robatsch Defense",
    "B07": "Robatsch Defense",
    "B08": "Robatsch Defense",
    "B09": "French Defense",
    "B10": "Caro-Kann Defense",
    "B11": "Caro-Kann Defense",
    "B12": "Caro-Kann Defense",
    "B13": "Caro-Kann Defense",
    "B14": "Caro-Kann Defense",
    "B15": "Caro-Kann Defense",
    "B16": "Caro-Kann Defense",
    "B17": "Caro-Kann Defense",
    "B18": "Caro-Kann Defense",
    "B19": "Caro-Kann Defense",
    "B20": "Sicilian Defense",
    "B21": "Sicilian Defense",
    "B22": "Sicilian Defense",
    "B23": "Sicilian Defense",
    "B24": "Sicilian Defense",
    "B25": "Sicilian Defense",
    "B26": "Sicilian Defense",
    "B27": "Sicilian Defense",
    "B28": "Sicilian Defense",
    "B29": "Sicilian Defense",
    "B30": "Sicilian Defense",
    "B31": "Sicilian Defense",
    "B32": "Sicilian Sveshnikov",
    "B33": "Sicilian Sveshnikov",
    "B34": "Sicilian Sveshnikov",
    "B35": "Sicilian Defense",
    "B36": "Sicilian Defense",
    "B37": "Sicilian Defense",
    "B38": "Sicilian Defense",
    "B39": "Sicilian Defense",
    "B40": "Sicilian Defense",
    "B41": "Sicilian Defense",
    "B42": "Sicilian Defense",
    "B43": "Sicilian Defense",
    "B44": "Sicilian Defense",
    "B45": "Sicilian Defense",
    "B46": "Sicilian Defense",
    "B47": "Sicilian Defense",
    "B48": "Sicilian Defense",
    "B49": "Sicilian Defense",
    "B50": "Sicilian Defense",
    "B51": "Sicilian Defense",
    "B52": "Sicilian Defense",
    "B53": "Sicilian Defense",
    "B54": "Sicilian Defense",
    "B55": "Sicilian Defense",
    "B56": "Sicilian Defense",
    "B57": "Sicilian Defense",
    "B58": "Sicilian Defense",
    "B59": "Sicilian Defense",
    "B60": "Sicilian Defense",
    "B61": "Sicilian Defense",
    "B62": "Sicilian Defense",
    "B63": "Sicilian Defense",
    "B64": "Sicilian Defense",
    "B65": "Sicilian Defense",
    "B66": "Sicilian Defense",
    "B67": "Sicilian Defense",
    "B68": "Sicilian Defense",
    "B69": "Sicilian Defense",
    "B70": "Sicilian Dragon",
    "B71": "Sicilian Dragon",
    "B72": "Sicilian Dragon",
    "B73": "Sicilian Dragon",
    "B74": "Sicilian Dragon",
    "B75": "Sicilian Dragon",
    "B76": "Sicilian Dragon",
    "B77": "Sicilian Dragon",
    "B78": "Sicilian Dragon",
    "B79": "Sicilian Dragon",
    "B80": "Sicilian Defense",
    "B81": "Sicilian Defense",
    "B82": "Sicilian Defense",
    "B83": "Sicilian Defense",
    "B84": "Sicilian Defense",
    "B85": "Sicilian Defense",
    "B86": "Sicilian Defense",
    "B87": "Sicilian Defense",
    "B88": "Sicilian Defense",
    "B89": "Sicilian Defense",
    "B90": "Sicilian Defense",
    "B91": "Sicilian Defense",
    "B92": "Sicilian Defense",
    "B93": "Sicilian Defense",
    "B94": "Sicilian Defense",
    "B95": "Sicilian Defense",
    "B96": "Sicilian Defense",
    "B97": "Sicilian Defense",
    "B98": "Sicilian Defense",
    "B99": "Sicilian Defense",
    
    # C-codes: 1.e4 e5
    "C00": "French Defense",
    "C01": "French Defense",
    "C02": "French Defense",
    "C03": "French Defense",
    "C04": "French Defense",
    "C05": "French Defense",
    "C06": "French Defense",
    "C07": "French Defense",
    "C08": "French Defense",
    "C09": "French Defense",
    "C10": "French Defense",
    "C11": "French Defense",
    "C12": "French Defense",
    "C13": "French Defense",
    "C14": "French Defense",
    "C15": "French Defense",
    "C16": "French Defense",
    "C17": "French Defense",
    "C18": "French Defense",
    "C19": "French Defense",
    "C20": "King's Pawn Opening",
    "C21": "Danish Gambit",
    "C22": "Center Game",
    "C23": "Bishop's Opening",
    "C24": "Bishop's Opening",
    "C25": "Vienna Game",
    "C26": "Vienna Game",
    "C27": "Vienna Game",
    "C28": "Vienna Game",
    "C29": "Vienna Game",
    "C30": "King's Gambit",
    "C31": "King's Gambit",
    "C32": "King's Gambit",
    "C33": "King's Gambit",
    "C34": "King's Gambit",
    "C35": "King's Gambit",
    "C36": "King's Gambit",
    "C37": "King's Gambit",
    "C38": "King's Gambit",
    "C39": "King's Gambit",
    "C40": "Scandinavian Defense",
    "C41": "Philidor Defense",
    "C42": "Russian Game",
    "C43": "Russian Game",
    "C44": "Scotch Game",
    "C45": "Scotch Game",
    "C46": "Three Knights Game",
    "C47": "Three Knights Game",
    "C48": "Four Knights Game",
    "C49": "Four Knights Game",
    "C50": "Italian Game",
    "C51": "Italian Game",
    "C52": "Italian Game",
    "C53": "Italian Game",
    "C54": "Italian Game",
    "C55": "Italian Game",
    "C56": "Italian Game",
    "C57": "Italian Game",
    "C58": "Italian Game",
    "C59": "Italian Game",
    "C60": "Ruy Lopez",
    "C61": "Ruy Lopez",
    "C62": "Ruy Lopez",
    "C63": "Ruy Lopez",
    "C64": "Ruy Lopez",
    "C65": "Ruy Lopez",
    "C66": "Ruy Lopez",
    "C67": "Ruy Lopez",
    "C68": "Ruy Lopez",
    "C69": "Ruy Lopez",
    "C70": "Ruy Lopez",
    "C71": "Ruy Lopez",
    "C72": "Ruy Lopez",
    "C73": "Ruy Lopez",
    "C74": "Ruy Lopez",
    "C75": "Ruy Lopez",
    "C76": "Ruy Lopez",
    "C77": "Ruy Lopez",
    "C78": "Ruy Lopez",
    "C79": "Ruy Lopez",
    "C80": "Ruy Lopez",
    "C81": "Ruy Lopez",
    "C82": "Ruy Lopez",
    "C83": "Ruy Lopez",
    "C84": "Ruy Lopez",
    "C85": "Ruy Lopez",
    "C86": "Ruy Lopez",
    "C87": "Ruy Lopez",
    "C88": "Ruy Lopez",
    "C89": "Ruy Lopez",
    "C90": "Ruy Lopez",
    "C91": "Ruy Lopez",
    "C92": "Ruy Lopez",
    "C93": "Ruy Lopez",
    "C94": "Ruy Lopez",
    "C95": "Ruy Lopez",
    "C96": "Ruy Lopez",
    "C97": "Ruy Lopez",
    "C98": "Ruy Lopez",
    "C99": "Ruy Lopez",
    
    # D-codes: 1.d4 d5
    "D00": "Closed Game",
    "D01": "Richter-Veresov",
    "D02": "Queen's Pawn Game",
    "D03": "Queen's Pawn Game",
    "D04": "Queen's Pawn Game",
    "D05": "Queen's Pawn Game",
    "D06": "Queen's Gambit Declined",
    "D07": "Queen's Gambit Declined",
    "D08": "Queen's Gambit Declined",
    "D09": "Queen's Gambit Declined",
    "D10": "Slav Defense",
    "D11": "Slav Defense",
    "D12": "Slav Defense",
    "D13": "Slav Defense",
    "D14": "Slav Defense",
    "D15": "Slav Defense",
    "D16": "Slav Defense",
    "D17": "Slav Defense",
    "D18": "Slav Defense",
    "D19": "Slav Defense",
    "D20": "Queen's Gambit Accepted",
    "D21": "Queen's Gambit Accepted",
    "D22": "Queen's Gambit Accepted",
    "D23": "Queen's Gambit Accepted",
    "D24": "Queen's Gambit Accepted",
    "D25": "Queen's Gambit Accepted",
    "D26": "Queen's Gambit Accepted",
    "D27": "Queen's Gambit Accepted",
    "D28": "Queen's Gambit Accepted",
    "D29": "Queen's Gambit Accepted",
    "D30": "Anti-Meran",
    "D31": "Semi-Slav",
    "D32": "Semi-Slav",
    "D33": "Semi-Slav",
    "D34": "Semi-Slav",
    "D35": "Semi-Slav",
    "D36": "Semi-Slav",
    "D37": "Queen's Gambit Declined",
    "D38": "Queen's Gambit Declined",
    "D39": "Queen's Gambit Declined",
    "D40": "Semi-Slav",
    "D41": "Semi-Slav",
    "D42": "Semi-Slav",
    "D43": "Semi-Slav",
    "D44": "Semi-Slav",
    "D45": "Semi-Slav",
    "D46": "Semi-Slav",
    "D47": "Semi-Slav",
    "D48": "Semi-Slav",
    "D49": "Semi-Slav",
    "D50": "Queen's Gambit Declined",
    "D51": "Queen's Gambit Declined",
    "D52": "Queen's Gambit Declined",
    "D53": "Queen's Gambit Declined",
    "D54": "Queen's Gambit Declined",
    "D55": "Queen's Gambit Declined",
    "D56": "Queen's Gambit Declined",
    "D57": "Queen's Gambit Declined",
    "D58": "Queen's Gambit Declined",
    "D59": "Queen's Gambit Declined",
    "D60": "Queen's Gambit Declined",
    "D61": "Queen's Gambit Declined",
    "D62": "Queen's Gambit Declined",
    "D63": "Queen's Gambit Declined",
    "D64": "Queen's Gambit Declined",
    "D65": "Queen's Gambit Declined",
    "D66": "Queen's Gambit Declined",
    "D67": "Queen's Gambit Declined",
    "D68": "Queen's Gambit Declined",
    "D69": "Queen's Gambit Declined",
    "D70": "Neo-Meran",
    "D71": "Neo-Meran",
    "D72": "Neo-Meran",
    "D73": "Neo-Meran",
    "D74": "Neo-Meran",
    "D75": "Neo-Meran",
    "D76": "Neo-Meran",
    "D77": "Neo-Meran",
    "D78": "Neo-Meran",
    "D79": "Neo-Meran",
    "D80": "Gruenfeld Defense",
    "D81": "Gruenfeld Defense",
    "D82": "Gruenfeld Defense",
    "D83": "Gruenfeld Defense",
    "D84": "Gruenfeld Defense",
    "D85": "Gruenfeld Defense",
    "D86": "Gruenfeld Defense",
    "D87": "Gruenfeld Defense",
    "D88": "Gruenfeld Defense",
    "D89": "Gruenfeld Defense",
    "D90": "Semi-Slav",
    "D91": "Semi-Slav",
    "D92": "Semi-Slav",
    "D93": "Semi-Slav",
    "D94": "Semi-Slav",
    "D95": "Semi-Slav",
    "D96": "Semi-Slav",
    "D97": "Semi-Slav",
    "D98": "Semi-Slav",
    "D99": "Semi-Slav",
    
    # E-codes: 1.e4 c5 and Indian Systems
    "E00": "Indian Defense",
    "E01": "Nimzo-Larsen Attack",
    "E02": "Nimzo-Larsen Attack",
    "E03": "Nimzo-Larsen Attack",
    "E04": "Nimzo-Larsen Attack",
    "E05": "Nimzo-Larsen Attack",
    "E06": "Catalan",
    "E07": "Catalan",
    "E08": "Catalan",
    "E09": "Catalan",
    "E10": "Anglo-Indian",
    "E11": "Bogo-Indian",
    "E12": "Queen's Indian",
    "E13": "Queen's Indian",
    "E14": "Queen's Indian",
    "E15": "Queen's Indian",
    "E16": "Queen's Indian",
    "E17": "Queen's Indian",
    "E18": "Queen's Indian",
    "E19": "Queen's Indian",
    "E20": "Nimzo-Indian",
    "E21": "Nimzo-Indian",
    "E22": "Nimzo-Indian",
    "E23": "Nimzo-Indian",
    "E24": "Nimzo-Indian",
    "E25": "Nimzo-Indian",
    "E26": "Nimzo-Indian",
    "E27": "Nimzo-Indian",
    "E28": "Nimzo-Indian",
    "E29": "Nimzo-Indian",
    "E30": "Nimzo-Indian",
    "E31": "Nimzo-Indian",
    "E32": "Nimzo-Indian",
    "E33": "Nimzo-Indian",
    "E34": "Nimzo-Indian",
    "E35": "Nimzo-Indian",
    "E36": "Nimzo-Indian",
    "E37": "Nimzo-Indian",
    "E38": "Nimzo-Indian",
    "E39": "Nimzo-Indian",
    "E40": "Nimzo-Indian",
    "E41": "Nimzo-Indian",
    "E42": "Nimzo-Indian",
    "E43": "Nimzo-Indian",
    "E44": "Nimzo-Indian",
    "E45": "Queen's Indian",
    "E46": "Queen's Indian",
    "E47": "Queen's Indian",
    "E48": "Queen's Indian",
    "E49": "Queen's Indian",
    "E50": "King's Indian",
    "E51": "King's Indian",
    "E52": "King's Indian",
    "E53": "King's Indian",
    "E54": "King's Indian",
    "E55": "King's Indian",
    "E56": "King's Indian",
    "E57": "King's Indian",
    "E58": "King's Indian",
    "E59": "King's Indian",
    "E60": "King's Indian",
    "E61": "King's Indian",
    "E62": "King's Indian",
    "E63": "King's Indian",
    "E64": "King's Indian",
    "E65": "King's Indian",
    "E66": "King's Indian",
    "E67": "King's Indian",
    "E68": "King's Indian",
    "E69": "King's Indian",
    "E70": "King's Indian",
    "E71": "King's Indian",
    "E72": "King's Indian",
    "E73": "King's Indian",
    "E74": "King's Indian",
    "E75": "King's Indian",
    "E76": "King's Indian",
    "E77": "King's Indian",
    "E78": "King's Indian",
    "E79": "King's Indian",
    "E80": "King's Indian Attack",
    "E81": "King's Indian Attack",
    "E82": "King's Indian Attack",
    "E83": "King's Indian Attack",
    "E84": "King's Indian Attack",
    "E85": "King's Indian Attack",
    "E86": "King's Indian Attack",
    "E87": "King's Indian Attack",
    "E88": "King's Indian Attack",
    "E89": "King's Indian Attack",
    "E90": "King's Indian",
    "E91": "King's Indian",
    "E92": "King's Indian",
    "E93": "King's Indian",
    "E94": "King's Indian",
    "E95": "King's Indian",
    "E96": "King's Indian",
    "E97": "King's Indian",
    "E98": "King's Indian",
    "E99": "King's Indian",
}


class ECOLoader:
    """Load and cache ECO codes to opening names"""
    
    _cache: Dict[str, str] = {}
    _loaded = False
    
    @classmethod
    def get_opening_name(cls, eco_code: Optional[str]) -> str:
        """
        Get opening name from ECO code.
        
        Args:
            eco_code: ECO code (e.g., 'B32', 'C45')
            
        Returns:
            Opening name or "Unknown Opening" if not found
        """
        if not eco_code:
            return "Unknown Opening"
        
        eco_code = eco_code.upper().strip()
        
        # Check cache first
        if eco_code in cls._cache:
            return cls._cache[eco_code]
        
        # Check database
        if eco_code in ECO_DATABASE:
            name = ECO_DATABASE[eco_code]
            cls._cache[eco_code] = name
            return name
        
        # Try prefix match (e.g., "C45a" -> "C45")
        if len(eco_code) > 3:
            prefix = eco_code[:3]
            if prefix in ECO_DATABASE:
                name = ECO_DATABASE[prefix]
                cls._cache[eco_code] = name
                return name
        
        logger.warning(f"ECO code not found: {eco_code}")
        return "Unknown Opening"
    
    @classmethod
    def get_all_codes(cls) -> Dict[str, str]:
        """Get all ECO codes and names"""
        return ECO_DATABASE.copy()
    
    @classmethod
    def clear_cache(cls):
        """Clear the cache"""
        cls._cache.clear()


# Convenience function
def get_opening_name(eco_code: Optional[str]) -> str:
    """Quick function to get opening name from ECO code"""
    return ECOLoader.get_opening_name(eco_code)
